config/routes.rb
Rails.application.routes.draw do
  get "dashboard", to: "user#dashboard"
  get "portfolio", to: "user#portfolio", as: "portfolio"

  get "stocks/turbo/:id", to: "stocks#turbo_show", as: "stock_turbo_show"
  get "stocks", to: "stocks#index", as: "stocks"
  get "stocks/:id", to: "stocks#show", as: "stock_details"
  post "orders/buy/:stock_id", to: "orders#buy", as: "buy_order"
  post "orders/sell/:stock_id", to: "orders#sell", as: "sell_order"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
        authenticated :user do
        root :to => 'user#dashboard', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'devise/sessions#new', as: :unauthenticated_root
      end
  end

  root "devise/sessions#new"
  get "error", to: "pages#error"
  get "admin", to: "admin#dashboard"
  get "admin/manage/:id", to: "admin#show", as: "show_user"
  get "admin/manage/:id/edit", to: "admin#edit", as: "edit_user"
  patch "admin/manage/:id", to: "admin#update", as: "update_user"
  delete "admin/manage/:id", to: "admin#destroy", as: "destroy_user"
  patch "admin/manage/:id/approve", to: "admin#approve", as: "approve_user"
  post 'deposit', to: 'user#deposit'
  post 'withdraw', to: 'user#withdraw'
  get "admin/transactions", to: "admin#transactions", as: "admin_transactions"
  get "orders", to: "orders#index", as: "orders"
  patch "orders/:id/cancel/:stock_id", to: "orders#cancel", as: "cancel_order"
end

app/views/admin/_admin_nav.html.erb
<div class='admin-nav-container'>
    <h1 class='admin-nav-header'>User Management</h1>

    <div class='admin-nav-profile'>
    <%= image_tag("dp.png", :class => "nav-dp") %>
    <span><%= current_user.email %></span>
    <%= button_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'user-row-actions sign-out-btn' %>
    </div>

</div>

app/views/admin/_stock_transactions.html.erb
<div class="admin-t-transactions-container">
      <h1>TRANSACTIONS</h1>
      <div class="admin-t-transaction-details">
        <div class="admin-t-transaction-details-header">
          <h3>SELLER</h3>
          <h3>BUYER</h3>
          <h3>PRICE</h3>
          <h3>QUANTITY</h3>
          <h3>ORDERED</h3>
        </div>
        <% @transactions.each do |transaction| %>
        <div class="admin-t-transaction-row">
          <p><%= transaction.seller.admin? ? "NONE" : transaction.seller.email %></p>
          <p><%= transaction.buyer.email %></p>
          <p><%= transaction.price %></p>
          <p><%= transaction.quantity %></p>
          <p><%= transaction.created_at.strftime("%H:%M:%S %a %m, %e") %></p>
        </div>
      <% end %>
      </div>
  </div>

app/views/admin/_user.html.erb
<div class='user-profile-container'>

<%= image_tag("dp.png", :class => "user-dp") %>
    
<div class='user-profile'>
    <div class='user-profile-details'>
        <strong><p class='user-profile-name'>
            <%= @user.first_name.capitalize %>
            <%= @user.last_name.capitalize %>
        </p></strong>
        <p class='user-profile-email'>
            <%= @user.email %>
        </p>
        <br/>
        <p class='user-profile-balance'>
            Balance: <%= @user.balance.floor(4) %> 
        </p>
    </div>
    <div class='show-user-actions'>
        <%= link_to "Edit Profile", edit_user_path(@user) %>
        <%= button_to "Delete Profile", destroy_user_path, method: :delete, class: 'delete-user-btn' %>
    </div>
</div>

</div>

app/views/admin/_user_nav.html.erb
<div class='user-nav-container'>
    <h1 class='user-nav-header'>
        User Management
    </h1>

    <div class='user-nav-profile'>
    <%= image_tag("dp.png", :class => "nav-dp") %>
    <span><%= current_user.email %></span>
    <%= button_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'user-row-actions sign-out-btn' %>
    </div>

</div>

app/views/admin/_user_row.html.erb
<%= turbo_frame_tag dom_id(user) do %>
<div class='user-row-container'>
  <div class='user-row'>
    <p class='user-row-name'><%= link_to user.first_name.capitalize, show_user_path(user.id), class: 'user-link'%></p>
    <p class='user-row-name'><%= link_to user.last_name.capitalize, show_user_path(user.id), class: 'user-link'%></p>
    <p class='user-row-email'><%= link_to user.email, show_user_path(user.id), class: 'user-link'%></p>
    <p class='user-row-status'><%= user.approved ? "Approved" : "Pending" %></p>
    <p class='user-row-actions'><% if user.approved %>
        <%= link_to "Edit Profile", edit_user_path(user), class: 'users-action-btns' %>
      <% else %>
        <%= link_to "Approve", approve_user_path(user), data: {"turbo-method": :patch, turbo_frame: dom_id(user)}, class: 'users-action-btns' %>
    <% end %>    
    </p>
  </div>
</div>  
<% end %>

app/views/admin/dashboard.html.erb
<div class='admin-dashboard'>
<%= render "user_nav" %>

<div class='admin-container'>

<div class='admin-features'>
  
  <%= link_to new_user_registration_path, class: 'admin-feature-link' do %>
  <div class='admin-feature add-user-btn'>
    <%= image_tag("add-user.png", :class => "feature-icon") %>
    <p><strong>Add User</strong></p>
  </div>
  <% end %>

  <%= link_to admin_transactions_path, class: 'admin-feature-link' do %>
  <div class='admin-feature add-user-btn'>
    <%= image_tag("logs.png", :class => "feature-icon") %>
    <p><strong>Transactions</strong></p>
  </div>
  <% end %>

  <div class='admin-feature'>
    <%= image_tag("report.png", :class => "feature-icon") %>
    <strong><span>Reports</span></strong>
  </div>

  <div class='admin-feature'>
    <%= image_tag("tool.png", :class => "feature-icon") %>
    <strong><span>Tools</span></strong>
  </div>

  <div class='admin-feature'>
    <%= image_tag("setting.png", :class => "feature-icon") %>
    <strong><span>Settings</span></strong>
  </div>

</div>

<div class='users-container'>
  <div class='users-headers'>
    <h2>First Name</h2>
    <h2>Last Name</h2>
    <h2>Email</h2>
    <h2 class='users-headers-status'>Status</h2>
    <h2 class='users-headers-actions'>Actions</h2>
  </div>
  <div class='user-container'>
  <% @users.each do |user| %>
    <%= render "user_row", user: user %>
  <% end %>
  </div>
</div>

</div>
</div>

app/views/admin/edit.html.erb
<div class="sign-up-container">

<%= form_for(:user, url: update_user_url, method: :patch, :html => {:class => 'sign-up-form', 'target' => 'signup'}) do |f| %>

  <div class="sign-up-content">

  <div class="sign-up-header">
  <p>ATLAS</p>
  <%= image_tag("ai3.png", :class => "sign-up-logo") %>
  <p>INDEX</p>
  </div>

  <div class="sign-up-body">

  <h2 class="sign-up-title">Edit</h2>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, maxlength: 20 %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, maxlength: 20 %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autocomplete: "email" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
    <p><%= link_to "Back", :back %></p>
  </div>
<% end %>

</div>
</div>
</div>

app/views/admin/show.html.erb
<div class='admin-show-users'>

<%= render "user_nav" %>

<%= render "user" %>

<div class='admin-user-portfolio-container'>

<div class='user-transactions'>

<div class='portfolio-header-container'>
    <h1 class='user-portfolio-header'>TRANSACTIONS</h1>
</div>

    <div class='user-transactions-container'>

    <div class='user-transactions-action'>
    <h2>BUY</h2>
    <div class='transaction-headers'>
        <span>Stock</span>
        <span>Price</span>
        <span>Quantity</span>
    </div>
    <div>
        <hr/>
    </div>
        <div class='transactions-details-container'>
            <%= render 'user/buy_transaction' %>
        </div>
    </div>

    <div>
        <hr/>
    </div>

    <div class='user-transactions-action'>
    <h2>SELL</h2>
    <div class='transaction-headers'>
        <span>Stock</span>
        <span>Price</span>
        <span>Quantity</span>
    </div>
    <div>
        <hr/>
    </div>
        <div class='transactions-details-container'>
            <%= render 'user/sell_transaction' %>
        </div>
    </div>

    </div>
</div>

<div class='user-portfolio'>

<div class='portfolio-header-container'>
    <h1 class='user-portfolio-header'>PORTFOLIO</h1>
</div>

<div class='user-portfolio-headers'>
    <span>Stock</span>
    <span>Quantity</span>
</div>
    
    <div>
        <hr/>
    </div>

    <div class='user-asset-container'>
        <%= render 'user/asset' %>
    </div>
</div>

</div>

<div class='back-btn'>
<%= link_to "Back", :back %>
</div>

</div>

app/views/admin/transactions.html.erb
<div class='admin-dashboard'>
<%= render "user_nav" %>

<div class='admin-transactions-view'>
<%= render "stock_transactions" %>
</div>

</div>