config/routes.rb
Rails.application.routes.draw do
  get "dashboard", to: "user#dashboard"
  get "portfolio", to: "user#portfolio", as: "portfolio"

  get "stocks/turbo/:id", to: "stocks#turbo_show", as: "stock_turbo_show"
  get "stocks", to: "stocks#index", as: "stocks"
  get "stocks/:id", to: "stocks#show", as: "stock_details"
  post "orders/buy/:stock_id", to: "orders#buy", as: "buy_order"
  post "orders/sell/:stock_id", to: "orders#sell", as: "sell_order"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
        authenticated :user do
        root :to => 'user#dashboard', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'devise/sessions#new', as: :unauthenticated_root
      end
  end

  root "devise/sessions#new"
  get "error", to: "pages#error"
  get "admin", to: "admin#dashboard"
  get "admin/manage/:id", to: "admin#show", as: "show_user"
  get "admin/manage/:id/edit", to: "admin#edit", as: "edit_user"
  patch "admin/manage/:id", to: "admin#update", as: "update_user"
  delete "admin/manage/:id", to: "admin#destroy", as: "destroy_user"
  patch "admin/manage/:id/approve", to: "admin#approve", as: "approve_user"
  post 'deposit', to: 'user#deposit'
  post 'withdraw', to: 'user#withdraw'
  get "admin/transactions", to: "admin#transactions", as: "admin_transactions"
  get "orders", to: "orders#index", as: "orders"
  patch "orders/:id/cancel/:stock_id", to: "orders#cancel", as: "cancel_order"
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :orders
  has_many :assets
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show turbo_show]
  before_action :authenticate_user!
  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
    # @transactions = Transaction.order(created_at: :desc)
  end

  # GET /stocks/1 or /stocks/1.json
  def show
    @order = Order.new
    @asset = current_user.assets.find_by(stock_id: @stock.id)
  end

  def turbo_show
    @stocks = Stock.all
    @buys = @stock.orders.buy.pending.includes(:user).order("users.role")
    @sells = @stock.orders.sell.pending.includes(:user).order("users.role")
    @transactions = Transaction.where(stock_id: @stock.id).order(created_at: :desc)
    @order = Order.new
    @asset = current_user.assets.find_by(stock_id: @stock.id)
    render partial: "index", status: :ok
  end

  private
    def set_stock
      @stock = Stock.find(params[:id])
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_index.html.erb
<%= turbo_frame_tag "stock_index_frame" do %>
<div class="stock-index-main-container">
  <nav class="stock-index-nav">
  <%= image_tag("ai3.png", :class => "stock-index-logo") %>
  <div class="stock-index-nav-middle">
    <p>My portfolio</p>
    <p>|</p>
    <p>Mutual funds</p>
    <p>|</p>
    <p>Support</p>
    <p>|</p>
    <p>Media</p>
  </div >
  <div class"stock-index-nav-right">
    <%= button_to "Sign out", destroy_user_session_path, :method => :delete %>
  </div>
  </nav>


  <div class="stock-index-main">
    <div class="stock-index-container">
      <div class="stock-index-table">
        <div class ="stock-index-name">
          <h1>STOCK</h1>
          <% @stocks.each do |stock| %>
            <%= link_to render("stock_row", stock: stock), stock_turbo_show_path(stock), remote: true, data: {"turbo-method": :get, "turbo_frame": "stock_index_frame"}%>
          <% end %>
        </div>
      </div>
      <div class="stock-index-order">
        <h1>ORDER BOOK</h1>
        <div class="stock-index-order-container">
        <div class="stock-index-order-buy">
        <h1>BUY</h1>
          <div class="buy-column-container">
          <div class="buy-column">
          <h1>PRICE</h1>
          <% @buys&.each do |order| %>
            <p><%=  order.price %></p>
          <% end %>
          </div>
          <div class="buy-column">
          <h1>QUANTITY</h1>
          <% @buys&.each do |order| %>
            <p><%=  order.quantity.floor(4) %></p>
          <% end %>
          </div>
        </div>
        </div>
        <div class="stock-index-order-sell">
        <h1>SELL</h1>
          <div class="sell-column-container">
            <div class="sell-column">
              <h1>PRICE</h1>
              <% @sells&.each do |order| %>
                <p><%=  order.price %></p>
              <% end %>
            </div>
            <div class="sell-column">
              <h1>QUANTITY</h1> 
              <% @sells&.each do |order| %>
                <p><%=  order.quantity.floor(4) %></p>
              <% end %>
            </div>  
          </div>
        </div>
      </div>


  </div>
  <div class='stock-index-trade-order'>
    <div class="stock-trade-container">
      <%= render "stock_trade_form", stock: @stock %>
    </div>

    <div class="transactions-container">
      <%= render "stock_transactions", transaction: @transactions %>
    </div>
  </div>

  </div>
</div>

<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <h1><%= stock.ticker %></h1>
  <h2><%= stock.company %></h2>
  <h3>USD <%= stock.price %></h3>
</div>

app/views/stocks/_stock_row.html.erb
<p><%= stock.ticker %></p>
<p>$<%= stock.price %></p>

app/views/stocks/_stock_trade_form.html.erb
  <div class="stock-frame-container">

  <% if current_user.approved %>

    <div>
      <% if stock %>
      <h3>Your Balance: <%= current_user.balance.floor(4).to_s %></h3>
        <div class="stock-frame-buy">
          <%= form_with model: @order, url: buy_order_path(stock.id), method: :post do |form| %>


          <div>
            <%= form.label :payment, style: "display: block" %>
            <%= form.number_field :price, step: :any, placeholder: "Max USD #{current_user.balance.floor(4)}" %>
          </div>
          
          <div>
            <%= form.submit "Buy #{stock.ticker}" %>
          </div>
        <% end %>
        <br>
        <%= form_with model: @order, url: buy_order_path(stock.id), method: :post do |form| %>
          <div>
            <%= form.label :quantity, style: "display: block" %>
            <%= form.number_field :quantity, step: :any, placeholder: "Max #{(current_user.balance/stock.price).floor(4)} units" %>
          </div>

          <div>
            <%= form.submit "Buy #{stock.ticker}" %>
          </div>
        <% end %>
        </div>

    <% if true %>
    <h3>Available <%= stock.ticker %> assets: <%= @asset&.quantity&.floor(4) || "0.0" %></h3>
      <div>
        <div class="stock-frame-sell">
          <%= form_with model: @order, url: sell_order_path(stock.id), method: :post do |form| %>

            <div>
              <%= form.label :payment, style: "display: block" %>
              <%= form.number_field :price, step: :any, placeholder: "Max USD #{@asset ? (@asset&.quantity * stock.price).floor(4) : '0.0'}" %>
            </div>

            <div>
              <%= form.submit "Sell #{stock.ticker}" %>
            </div>
          <% end %>
          <br>
          <%= form_with model: @order, url: sell_order_path(stock.id), method: :post do |form| %>
            <div>
              <%= form.label :quantity, style: "display: block" %>
              <%= form.number_field :quantity, step: :any, placeholder: "Max #{@asset&.quantity&.floor(4) or '0.0'} units"  %>
            </div>

            <div>
              <%= form.submit "Sell #{stock.ticker}" %>
            </div>
          <% end %> 
          </div> 
        <% end %>
      </div>
    
    </div>
    <% else %>
      <div>
        <h1>Please choose a stock to trade</h1>
      </div>
      <% end %>

    <% else %>
      <div>
        <h1>Trading access is only granted to approved accounts. Please await approval by an administrator.</h1>
      </div>

    <% end %>

  </div>

app/views/stocks/_stock_transactions.html.erb
<div class="transactions-container">
      <h1>TRANSACTIONS</h1>
      <div class="transaction-details">
        <div class="transaction-details-header">
          <h3>PRICE</h3>
          <h3>QUANTITY</h3>
          <h3>ORDERED</h3>
        </div>
        <% @transactions&.each do |transaction| %>
        <div class="transaction-row">
          <p><%= transaction.price %></p>
          <p><%= transaction.quantity %></p>
          <p><%= transaction.created_at.strftime("%H:%M:%S %a %m, %e") %></p>
        </div>
      <% end %>
      </div>
  </div>

app/views/stocks/index.html.erb
<%= render "index" %>

app/views/stocks/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @stock.ticker %></h1>
<h2><%= @stock.company %></h2>
<h3>USD <%= @stock.price %></h3>
<p>There are <span><%= @stock.orders.buy.pending.count %></span> Buy orders for this stock</p>
<% @stock.orders.buy.pending.each do |order| %>
  <span>Order No.: <%= order.id %></span>
  <span>Offer: USD <%= order.price %></span>
  <span>Qt: <%= order.quantity %></span>
<% end %>

<p>There are <span><%= @stock.orders.sell.pending.count %></span> Sell orders for this stock</p>
<% @stock.orders.sell.pending.each do |order| %>
  <span>Order No.: <%= order.id %></span>
  <span>Asking: USD <%= order.price %></span>
  <span>Qt: <%= order.quantity %></span>
<% end %>

<div style="display: flex; padding: 20px;">
  <div>
  <%= form_with model: @order, url: buy_order_path(@stock.id), method: :post do |form| %>
    <h3>Your Balance: <%= current_user.balance.floor(4) %></h3>

    <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.number_field :price, value: @stock.price, step: :any %>
    </div>
    
    <div>
      <%= form.submit "Buy #{@stock.ticker}" %>
    </div>
  <% end %>
  <br>
  <%= form_with model: @order, url: buy_order_path(@stock.id), method: :post do |form| %>
    <div>
      <%= form.label :quantity, style: "display: block" %>
      <%= form.number_field :quantity, step: :any, placeholder: "Max #{(current_user.balance/@stock.price).floor(4)} units" %>
    </div>

    <div>
      <%= form.submit "Buy #{@stock.ticker}" %>
    </div>
  <% end %>
  </div>

  <% if @asset %>
    <div>
    <%= form_with model: @order, url: sell_order_path(@stock.id), method: :post do |form| %>
      <h3>Available <%= @stock.ticker %> assets: <%= @asset.quantity.floor(4) %></h3>

      <div>
        <%= form.label :price, style: "display: block" %>
        <%= form.number_field :price, step: :any, placeholder: "Max USD #{(@asset.quantity * @stock.price).floor(4)}" %>
      </div>

      <div>
        <%= form.submit "Sell #{@stock.ticker}" %>
      </div>
    <% end %>
    <br>
    <%= form_with model: @order, url: sell_order_path(@stock.id), method: :post do |form| %>
      <div>
        <%= form.label :quantity, style: "display: block" %>
        <%= form.number_field :quantity, step: :any, value: @asset.quantity.floor(4) %>
      </div>

      <div>
        <%= form.submit "Sell #{@stock.ticker}" %>
      </div>
    <% end %> 
    </div> 
  <% end %>
  
</div>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>