config/routes.rb
Rails.application.routes.draw do
  get "dashboard", to: "user#dashboard"
  get "portfolio", to: "user#portfolio", as: "portfolio"

  get "stocks/turbo/:id", to: "stocks#turbo_show", as: "stock_turbo_show"
  get "stocks", to: "stocks#index", as: "stocks"
  get "stocks/:id", to: "stocks#show", as: "stock_details"
  post "orders/buy/:stock_id", to: "orders#buy", as: "buy_order"
  post "orders/sell/:stock_id", to: "orders#sell", as: "sell_order"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
        authenticated :user do
        root :to => 'user#dashboard', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'devise/sessions#new', as: :unauthenticated_root
      end
  end

  root "devise/sessions#new"
  get "error", to: "pages#error"
  get "admin", to: "admin#dashboard"
  get "admin/manage/:id", to: "admin#show", as: "show_user"
  get "admin/manage/:id/edit", to: "admin#edit", as: "edit_user"
  patch "admin/manage/:id", to: "admin#update", as: "update_user"
  delete "admin/manage/:id", to: "admin#destroy", as: "destroy_user"
  patch "admin/manage/:id/approve", to: "admin#approve", as: "approve_user"
  post 'deposit', to: 'user#deposit'
  post 'withdraw', to: 'user#withdraw'
  get "admin/transactions", to: "admin#transactions", as: "admin_transactions"
  get "orders", to: "orders#index", as: "orders"
  patch "orders/:id/cancel/:stock_id", to: "orders#cancel", as: "cancel_order"
end

app/models/order.rb
class Order < ApplicationRecord
  scope :buy, -> { where(action: 0) }
  scope :sell, -> { where(action: 1) }
  scope :pending, -> { where(status: 0) }
  scope :by_admin, -> { where(user: User.find_by(role: 1), action: 1, status: 0) }
  enum action: [:buy, :sell]
  enum status: [:pending, :success, :cancelled]
  belongs_to :user
  belongs_to :stock
  validates :action, :quantity, :price, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[ show edit update destroy cancel ]
  before_action :set_stock, except: %i[ index cancel ]
  before_action :set_order_details, only: %i[ buy sell ]
  before_action :set_orders, only: %i[ index cancel ]

  # GET /orders or /orders.json
  def index
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
  end

  # POST /orders/buy/:stock_id
  def buy
    @order.action = 0
    orders = active_orders_for(@order).sell

    respond_to do |format|
      if @order.price * @order.quantity > current_user.balance
        format.html { redirect_to stock_turbo_show_url(@stock), notice: "Insufficient balance." }
      elsif @order.save
        current_user.balance -= @order.price * @order.quantity
        current_user.save
        if !orders.empty?
          required_quantity = @order.quantity
          accumulated_quantity = 0.0
          orders.each do |order|
            if accumulated_quantity >= @order.quantity
              break
            elsif order.quantity >= required_quantity
              Transaction.create(buyer: current_user, seller: order.user, stock: @stock, price: @order.price, quantity: required_quantity)
              order.user.update(balance: order.user.balance + required_quantity * order.price)
              order.quantity -= required_quantity
              order.status = 1 if order.quantity == 0.0
              order.save
              accumulated_quantity += required_quantity
              required_quantity = 0.0
            elsif order.quantity < required_quantity
              Transaction.create(buyer: current_user, seller: order.user, stock: @stock, price: @order.price, quantity: order.quantity)
              required_quantity -= order.quantity
              accumulated_quantity += order.quantity
              order.user.update(balance: order.user.balance + order.quantity * order.price)
              order.update(quantity: 0.0, status: 1)
            end
          end
          @order.status = 1 if accumulated_quantity >= @order.quantity
          @order.quantity -= accumulated_quantity
          @asset.quantity += accumulated_quantity
          @order.save
          @asset.save
          format.html { redirect_to stock_turbo_show_url(@stock), notice: "Order has been #{"partially" if required_quantity > 0.0} fulfilled." }
        else
          format.html { redirect_to stock_turbo_show_url(@stock), notice: "Order has been posted." } 
        end
      else
        format.html { render :create, notice: "Cannot process order.", status: :unprocessable_entity }
      end
    end
  end

  # POST /orders/sell/:stock_id
  def sell
    @order.action = 1
    orders = active_orders_for(@order).buy

    respond_to do |format|
      if @order.quantity > @asset.quantity
        format.html { redirect_to stock_turbo_show_url(@stock), notice: "Insufficient assets." }
      elsif @order.save
        @asset.quantity -= @order.quantity
        @asset.save
        if !orders.empty?
          required_quantity = @order.quantity
          accumulated_quantity = 0.0
          orders.each do |order|
            asset = order.user.assets.find_by(stock_id: @stock.id)
            if accumulated_quantity >= @order.quantity
              break
            elsif order.quantity >= required_quantity
              Transaction.create(buyer: order.user, seller: current_user, stock: @stock, price: @order.price, quantity: required_quantity)
              asset.update(quantity: asset.quantity + required_quantity)
              order.quantity -= required_quantity
              order.status = 1 if order.quantity == 0.0
              order.save
              accumulated_quantity += required_quantity
              required_quantity = 0.0
            elsif order.quantity < required_quantity
              Transaction.create(buyer: order.user, seller: current_user, stock: @stock, price: @order.price, quantity: order.quantity)
              required_quantity -= order.quantity
              accumulated_quantity += order.quantity
              asset.update(quantity: asset.quantity + order.quantity)
              order.update(quantity: 0.0, status: 1)
            end
          end
          @order.status = 1 if accumulated_quantity >= @order.quantity
          @order.quantity -= accumulated_quantity
          current_user.balance += @order.price * accumulated_quantity
          @order.save
          current_user.save
          format.html { redirect_to stock_turbo_show_url(@stock), notice: "Order has been #{"partially" if required_quantity > 0.0} fulfilled." }
        else
          format.html { redirect_to stock_turbo_show_url(@stock), notice: "Order has been posted." } 
        end
      else
        format.html { render :create, notice: "Cannot process order.", status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH /orders/cancel/:id
  def cancel
    if @order.action == 0
      @order.update(status: 2)
      current_user.balance += @order.price
      current_user.save
    else
      @order.update(status: 2)
      asset = current_user.assets.find_by(stock_id: Stock.find(params[:stock_id]))
      asset.quantity += @order.quantity
      asset.save
    end
    render partial: "order_table", locals: {orders: @orders}, status: :ok
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def set_orders
      @orders = current_user.orders.order(status: :asc)
    end

    def set_stock
      @stock = Stock.find(params[:stock_id])
    end

    def order_params
      params.require(:order).permit(:quantity, :price)
    end

    def set_order_details
      @asset = current_user.assets.find_by(stock_id: @stock.id)
      @asset = Asset.create(user: current_user, stock: @stock, quantity: 0.0) if !@asset
      @price = order_params[:price]
      @quantity = order_params[:quantity]
      @order = Order.new(status: 0, user: current_user, stock: @stock, price: @stock.price)
      @order.quantity = @quantity ? @quantity.to_f : @price.to_f/@stock.price.to_f
    end
    
    def active_orders_for order
      orders = @stock.orders.where.not(user: current_user).where(price: order.price).pending.includes(:user).order("users.role")
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :action, style: "display: block" %>
    <%= form.number_field :action %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :stock_id, style: "display: block" %>
    <%= form.text_field :stock_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Action:</strong>
    <%= order.action %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= order.price %>
  </p>


  <p>
    <strong>Quantity:</strong>
    <%= order.quantity %>
  </p>

</div>

app/views/orders/_order_table.html.erb
<%= turbo_frame_tag "orders_table_frame" do %>
  <div>
    <% orders.each do |order| %>
      <div class='orders-container'>
        <p><%= order.action.capitalize %></p>
        <p><%= order.stock.ticker %></p>
        <p><%= order.quantity.floor(4) %></p>
        <p>USD <%= order.price.floor(4) %></p>
        <% if order.pending? %>
          <%= link_to "Cancel", cancel_order_path(order.id, order.stock.id), data: {"turbo-method": :patch, turbo_frame: "orders_table_frame" }%>
        <% else %>
          <p><%= order.status.capitalize %></p>
        <% end %>
        
      </div>
    <% end %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<%= render 'order_table', orders: @orders %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>