config/routes.rb
Rails.application.routes.draw do
  get "dashboard", to: "user#dashboard"
  get "portfolio", to: "user#portfolio", as: "portfolio"

  get "stocks/turbo/:id", to: "stocks#turbo_show", as: "stock_turbo_show"
  get "stocks", to: "stocks#index", as: "stocks"
  get "stocks/:id", to: "stocks#show", as: "stock_details"
  post "orders/buy/:stock_id", to: "orders#buy", as: "buy_order"
  post "orders/sell/:stock_id", to: "orders#sell", as: "sell_order"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
        authenticated :user do
        root :to => 'user#dashboard', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'devise/sessions#new', as: :unauthenticated_root
      end
  end

  root "devise/sessions#new"
  get "error", to: "pages#error"
  get "admin", to: "admin#dashboard"
  get "admin/manage/:id", to: "admin#show", as: "show_user"
  get "admin/manage/:id/edit", to: "admin#edit", as: "edit_user"
  patch "admin/manage/:id", to: "admin#update", as: "update_user"
  delete "admin/manage/:id", to: "admin#destroy", as: "destroy_user"
  patch "admin/manage/:id/approve", to: "admin#approve", as: "approve_user"
  post 'deposit', to: 'user#deposit'
  post 'withdraw', to: 'user#withdraw'
  get "admin/transactions", to: "admin#transactions", as: "admin_transactions"
  get "orders", to: "orders#index", as: "orders"
  patch "orders/:id/cancel/:stock_id", to: "orders#cancel", as: "cancel_order"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true
  enum role: [:trader, :admin]
  has_many :orders
  has_many :assets
  has_many :buyer_transactions, class_name: 'Transaction', foreign_key: 'buyer_id'
  has_many :seller_transactions, class_name: 'Transaction', foreign_key: 'seller_id'

  # def active_for_authentication? 
  #   super && approved?
  # end 
    
  # def inactive_message 
  #   approved? ? super : :not_approved
  # end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user 
    before_action :form_params
    before_action :check_status

    def dashboard
    end

    def deposit
        current_user.balance += form_params[:amount].to_f
        current_user.save
        render partial: "dashboard", locals: {balance: current_user.balance}, status: :ok
    end

    def withdraw
        if current_user.balance >= form_params[:amount].to_f
            current_user.balance -= form_params[:amount].to_f
            current_user.save
            render partial: "dashboard", locals: {balance: current_user.balance}, status: :ok
        end
    end

    def form_params
        params
    end

    def trade
    end

    def portfolio
        @buy_transactions = @user.buyer_transactions
        @sell_transactions = @user.seller_transactions
        @assets = @user.assets
        @orders = @user.orders.order(status: :asc)
    end

    private

    def set_user
        @user = current_user
    end

    def check_status
        if !@user.approved
            redirect_to stocks_path
        end
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  # before_action :authenticate_user!, :redirect_unless_admin,  only: [:new, :create]
  # skip_before_action :require_no_authentication
  skip_before_action :require_no_authentication, only: [:new, :create]

  # GET /resource/sign_up
  def new
    if !current_user || current_user.admin?
      super
    else
      redirect_to root_path
    end
  end

  # POST /resource
  def create
    if !current_user || current_user.admin?
      build_resource(sign_up_params)
      
      if current_user&.admin?
        resource.approved = true
      end

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.approved
        notice = current_user && current_user.admin? ? :signed_up_through_admin : :signed_up
        set_flash_message! :notice, notice
        sign_up(resource_name, resource) 
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        UserMailer.with(user: resource).welcome.deliver_later
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end

  
    else
      redirect_to root_path
    end
  end

  # GET /resource/edit
  def edit
    if current_user && current_user.admin?
      @user = User.find(params[:id])
    end
    super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def sign_up(resource_name, resource)
    true
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    if current_user&.admin?
      admin_path
    else
      root_path
    end
  end

  # # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate(auth_options)
    if self.resource.nil?
      flash[:alert] = I18n.t('devise.failure.not_found_in_database', authentication_keys: 'email')
      redirect_to root_path
    else
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_asset.html.erb
<% @assets.each do |asset| %>
    <div class='asset-container'>
        <span><%= asset.stock.ticker %></span>
        <span><%= asset.quantity %></span>
    </div>
<% end %>

app/views/user/_balance.html.erb
<span><%= balance.floor(4) %></span>

app/views/user/_bank_form_nav.html.erb
<div class="bank-form-nav">
    <p>ATLAS</p>
    <%= image_tag("ai3.png", :class => "bank-form-logo") %>
    <p>INDEX</p>
</div>
    

app/views/user/_buy_transaction.html.erb
<% @buy_transactions.each do |buy_transaction| %>
    <div class='transactions-details'>
        <span><%= buy_transaction.stock.ticker %></span>
        <span><%= buy_transaction.price %></span>
        <span><%= buy_transaction.quantity %></span>
    </div>
<% end %>

app/views/user/_dashboard.html.erb
<%= turbo_frame_tag "dashboard_frame" do %>
<div class='user-dashboard'>
<%= render 'user_nav' %>

<div class='user-features'>

  <div class='user-feature'>
    <strong><%= link_to 'Deposit', nil, remote: true,
      data: {
        controller: "bank",
        action: "bank#deposit",
        bank_form_param: "new-deposit-form",
        bank_backdrop_param: "new-bank-backdrop"
      } %></strong>
  </div>

  <div class='user-feature'>
    <strong><%= link_to 'Withdraw', nil, remote: true,
      data: {
        controller: "bank",
        action: "bank#withdraw",
        bank_form_param: "new-withdraw-form",
        bank_backdrop_param: "new-bank-backdrop"
      } %></strong>
  </div>

  <div class='user-feature'>
    <strong><%= link_to 'Trade', stocks_path %></strong>
  </div>

  <div class='user-feature'>
    <strong><%= link_to 'Portfolio', portfolio_path %></strong>
  </div>

  <div id="new-deposit-form" class="d-none new-bank-form">
    <%= render 'user/deposit_form'%>
  </div>

  <div id="new-withdraw-form" class="d-none new-bank-form">
    <%= render 'user/withdraw_form'%>
  </div>

</div>

<%= link_to "", nil, remote: true, class: "d-none new-bank-backdrop", id: 'new-bank-backdrop',
  data: {
    controller: "bank",
    action: "bank#hideForm",
    bank_form_param: "new-bank-form",
    bank_backdrop_param: "new-bank-backdrop"
  } %>

</div>


<% end %>

app/views/user/_deposit_form.html.erb
<%= form_with(url: deposit_path, method: :post) do |form| %>

  <%= render 'bank_form_nav' %>

<div class='bank-form'>
  <h1>Deposit</h1>

  <div class='bank-form-details'>
    <div class='bank-balance'>
      Balance: <%= render 'balance', balance: current_user.balance.floor(4) %>
    </div>

    <div class='bank-amount'>
    <div>
      <%= form.number_field :amount, placeholder: "Enter amount", class: 'bank-form-amount' %>
    </div>

    <div class='bank-form-save'>
      <%= form.submit 'Save', data: {"turbo-method": :post, turbo_frame: "dashboard_frame" } %>
    </div>
    </div>
  </div>
</div>

<% end %>

app/views/user/_sell_transaction.html.erb
<% @sell_transactions.each do |sell_transaction| %>
    <div class='transactions-details'>
        <span><%= sell_transaction.stock.ticker %></span>
        <span><%= sell_transaction.price %></span>
        <span><%= sell_transaction.quantity %></span>
    </div>
<% end %>

app/views/user/_user_nav.html.erb
<div class='user-nav-container'>
    <h1 class='user-nav-header'>User Dashboard</h1>

    <div class='user-nav-profile'>
    <%= image_tag("dp.png", :class => "nav-dp") %>
    <span><%= current_user.email %></span>
    <span><strong>USD <%= current_user.balance.floor(4) %></strong></span>
    <%= button_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'user-row-actions sign-out-btn' %>
    </div>

</div>

app/views/user/_withdraw_form.html.erb
<%= form_with(url: withdraw_path, method: :post) do |form| %>

  <%= render 'bank_form_nav' %>

<div class='bank-form'> 
  <h1>Withdraw</h1>

<div class='bank-form-details'>
  <div class='bank-balance'>
    Balance: <%= render 'balance', balance: current_user.balance.floor(4) %>
  </div>

  <div class='bank-amount'>
  <div>
    <%= form.number_field :amount, placeholder: "Enter amount", class: 'bank-form-amount' %>
  </div>

  <div class='bank-form-save'>
    <%= form.submit "Save", data: {"turbo-method": :post, turbo_frame: "dashboard_frame" }  %>
  </div>
  </div>
</div>
</div>

<% end %>

app/views/user/dashboard.html.erb
<%= render "dashboard" %>

app/views/user/portfolio.html.erb
<div class='user-dashboard'>
<%= render 'user_nav' %>

<div class='user-portfolio-container'>

<div class='user-transactions'>

<div class='portfolio-header-container'>
    <h1 class='user-portfolio-header'>TRANSACTIONS</h1>
</div>

    <div class='user-transactions-container'>

    <div class='user-transactions-action'>
    <h2>BUY</h2>
    <div class='transaction-headers'>
        <span>Stock</span>
        <span>Price</span>
        <span>Quantity</span>
    </div>
    <div>
        <hr/>
    </div>
        <div class='transactions-details-container'>
            <%= render 'buy_transaction' %>
        </div>
    </div>

    <div>
        <hr/>
    </div>

    <div class='user-transactions-action'>
    <h2>SELL</h2>
    <div class='transaction-headers'>
        <span>Stock</span>
        <span>Price</span>
        <span>Quantity</span>
    </div>
    <div>
        <hr/>
    </div>
        <div class='transactions-details-container'>
            <%= render 'sell_transaction' %>
        </div>
    </div>

    </div>
</div>

<div class='user-orders'>
<div class='portfolio-header-container'>
    <h1 class='user-portfolio-header'>ORDERS</h1>
</div>

<div class='user-order-headers'>
    <span>Action</span>
    <span>Stock</span>
    <span>Quantity</span>
    <span>Price</span>
    <span>Status</span>
</div>
    
    <div>
        <hr/>
    </div>
    <div class='user-orders-container'>
    <%= render 'orders/order_table', orders: @orders %>
    </div>
</div>

<div class='user-portfolio'>

<div class='portfolio-header-container'>
    <h1 class='user-portfolio-header'>PORTFOLIO</h1>
</div>

<div class='user-portfolio-headers'>
    <span>Stock</span>
    <span>Quantity</span>
</div>
    
    <div>
        <hr/>
    </div>

    <div class='user-asset-container'>
        <%= render 'asset' %>
    </div>
</div>

</div>

</div>